# Generated by Django 2.1 on 2019-08-25 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunitySchoolRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareshiksha.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('community', models.TextField()),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('students_no', models.IntegerField()),
                ('teacher_no', models.IntegerField()),
                ('resource1_no', models.IntegerField()),
                ('resource2_no', models.IntegerField()),
                ('resource3_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareshiksha.School')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('skill_name', models.CharField(max_length=30)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareshiksha.Community')),
            ],
        ),
        migrations.AddField(
            model_name='communityschoolrel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareshiksha.School'),
        ),
        migrations.AddField(
            model_name='admin',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareshiksha.Community'),
        ),
    ]
