# Generated by Django 2.1 on 2019-08-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareshiksha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='community_name',
            field=models.TextField(default='varanasi1'),
        ),
    ]
